# Generated by Django 4.1.4 on 2023-02-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otozeusapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
