# Generated by Django 4.1.4 on 2023-01-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otozeusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='video',
            field=models.FileField(max_length=255, upload_to='uploads/'),
        ),
    ]
