# Generated by Django 4.1.4 on 2023-01-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otozeusapp', '0003_alter_demo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
