# Generated by Django 4.1.4 on 2023-01-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otozeusapp', '0005_alter_demo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='video',
            field=models.FileField(max_length=255, upload_to='uploads/'),
        ),
    ]
